"""
Magic Link Verification Endpoint — browser callback for OOB gate approvals.

Sprint 199 — Track A, A-05.

When a user requests gate approval via OTT chat, the governance_action_handler
generates a Magic Link (HMAC-SHA256 signed, 5-min TTL, single-use). The user
clicks the link in their browser, which hits this endpoint to:

    1. Validate the HMAC token signature
    2. Check 5-min TTL expiry
    3. Consume the token atomically (single-use via Redis GETDEL)
    4. Verify browser session user matches token user
    5. Execute the gate action (approve/reject)
    6. Return confirmation page / JSON response

Security references:
    - ADR-064 D-064-04: HMAC-SHA256 tokens, 5-min expiry, single-use
    - STM-064 C1: Magic Link Token Guessing mitigation
    - STM-064 C4: OOB Auth Bypass mitigation
    - FR-047: Magic Link OOB Auth functional requirement
"""

from __future__ import annotations

import logging
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.services.agent_team.magic_link_service import (
    MagicLinkExpiredError,
    MagicLinkInvalidError,
    MagicLinkService,
    MagicLinkUserMismatchError,
)
from app.services.gate_service import GateNotFoundError, GateService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/magic-link", tags=["Magic Link"])


@router.get(
    "/verify",
    summary="Verify and consume a Magic Link token for gate approval",
    response_description="Gate action result after token verification",
)
async def verify_magic_link(
    token: str = Query(
        ...,
        min_length=64,
        max_length=64,
        description="HMAC-SHA256 token signature (64 hex chars)",
    ),
    user_id: str = Query(
        ...,
        min_length=1,
        description="Authenticated user ID from browser session",
    ),
    db: AsyncSession = Depends(get_db),
) -> JSONResponse:
    """
    Verify a Magic Link token and execute the gate action.

    This endpoint is called when the user clicks the Magic Link URL
    generated by the governance action handler. The token is validated
    and consumed atomically (single-use).

    Query params:
        token: 64-char hex HMAC-SHA256 signature
        user_id: Browser session user ID (must match token issuer)

    Returns:
        200: Gate action executed successfully
        400: Invalid token format
        403: User mismatch (token issued for different user)
        410: Token expired or already used
    """
    ml_service = MagicLinkService()

    # 1. Validate and consume token (atomic GET + DELETE)
    try:
        payload = await ml_service.validate_and_consume(
            signature=token,
            browser_user_id=user_id,
        )
    except MagicLinkInvalidError as exc:
        logger.warning("magic_link_verify: invalid token error=%s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid magic link token.",
        )
    except MagicLinkExpiredError as exc:
        logger.info("magic_link_verify: expired/used token")
        raise HTTPException(
            status_code=status.HTTP_410_GONE,
            detail="Magic link expired or already used. Please request a new one via chat.",
        )
    except MagicLinkUserMismatchError as exc:
        logger.warning("magic_link_verify: user mismatch")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This magic link was issued for a different user.",
        )

    # 2. Execute gate action
    gate_svc = GateService(db)
    gate_id = UUID(payload.gate_id)
    approver_id = UUID(payload.user_id)
    action = payload.action

    try:
        gate = await gate_svc.get_gate_by_id(gate_id)
        if not gate:
            raise GateNotFoundError(f"Gate {gate_id} not found")

        if action == "approve":
            updated_gate = await gate_svc.approve_gate(
                gate_id=gate_id,
                approver_id=approver_id,
            )
            action_label = "APPROVED"
        elif action == "reject":
            updated_gate = await gate_svc.reject_gate(
                gate_id=gate_id,
                approver_id=approver_id,
                rejection_reason="Rejected via Magic Link (OTT chat)",
            )
            action_label = "REJECTED"
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Unknown action: {action}",
            )

    except GateNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Gate {gate_id} not found.",
        )
    except Exception as exc:
        logger.error(
            "magic_link_verify: gate action failed gate_id=%s action=%s error=%s",
            gate_id, action, str(exc),
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to execute gate action: {str(exc)[:200]}",
        )

    gate_type = getattr(updated_gate, "gate_type", None) or getattr(updated_gate, "gate_code", "?")
    gate_name = getattr(updated_gate, "gate_name", "") or gate_type

    logger.info(
        "magic_link_verify: gate %s %s by user %s via magic link",
        gate_id, action_label, approver_id,
    )

    return JSONResponse(
        content={
            "status": "success",
            "gate_id": str(gate_id),
            "gate_name": gate_name,
            "gate_type": gate_type,
            "action": action_label,
            "message": f"Gate {gate_name} has been {action_label} via Magic Link.",
            "approved_by": str(approver_id),
        },
        status_code=status.HTTP_200_OK,
    )
