"""
=========================================================================
Auto-Generation Service - Compliance Artifact Generators
SDLC Orchestrator - Sprint 108 (Governance Foundation)

Version: 1.0.0
Date: January 27, 2026
Status: ACTIVE - Sprint 108 Day 2
Authority: CTO + Backend Lead Approved
Framework: SDLC 5.3.0 Quality Assurance System

Purpose:
- Generate compliance artifacts automatically to reduce developer friction
- Implement 4 generators: Intent, Ownership, Context, Attestation
- Apply fail-safe chain: LLM -> Template -> Minimal Placeholder

CORE PRINCIPLE:
  "GOVERNANCE MUST BE THE FASTEST WAY"
  Target: <5 minutes per PR (80% faster than 30 min baseline)

FAIL-SAFE PRINCIPLE:
  "AUTO-GENERATION MAY FAIL, BUT GOVERNANCE MUST NEVER HARD-BLOCK"
  Guarantee: Developer can proceed within 2 minutes

Zero Mock Policy: Real implementations with Ollama integration
=========================================================================
"""

import hashlib
import logging
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional
from uuid import UUID

import yaml

from app.core.config import settings
from app.services.ollama_service import OllamaService, OllamaError, get_ollama_service

logger = logging.getLogger(__name__)


# ============================================================================
# Enums and Data Classes
# ============================================================================


class FallbackLevel(str, Enum):
    """
    Fallback level indicates how the content was generated.

    Level 1 (LLM): Best quality, AI-generated
    Level 2 (Template): Good quality, deterministic template
    Level 3 (Minimal): Basic structure, requires manual editing
    """

    LLM = "llm"
    TEMPLATE = "template"
    MINIMAL = "minimal"


class GeneratorType(str, Enum):
    """Types of compliance artifact generators."""

    INTENT = "intent_skeleton"
    OWNERSHIP = "ownership_suggestion"
    CONTEXT = "context_attachment"
    ATTESTATION = "attestation_template"


@dataclass
class GenerationResult:
    """
    Result from any auto-generation operation.

    Attributes:
        success: Whether generation completed (any level)
        fallback_level: Which fallback level was used
        content: Generated content (markdown, annotation, etc.)
        confidence: Confidence score (0-100)
        latency_ms: Generation time in milliseconds
        generator_type: Which generator produced this result
        metadata: Additional context-specific metadata
        error: Error message if generation failed entirely
    """

    success: bool
    fallback_level: FallbackLevel
    content: str
    confidence: int
    latency_ms: float
    generator_type: GeneratorType
    metadata: dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def ui_badge(self) -> dict[str, str]:
        """
        Return UI badge based on fallback level.

        Returns:
            Dict with 'color' and 'text' for UI display
        """
        badges = {
            FallbackLevel.LLM: {
                "color": "green",
                "text": "Auto-generated by AI",
            },
            FallbackLevel.TEMPLATE: {
                "color": "yellow",
                "text": "Generated from template. Please review.",
            },
            FallbackLevel.MINIMAL: {
                "color": "orange",
                "text": "Auto-generation failed. Manual input required.",
            },
        }
        return badges.get(self.fallback_level, badges[FallbackLevel.MINIMAL])


@dataclass
class TaskContext:
    """Task context for intent generation."""

    task_id: str
    title: str
    description: str
    acceptance_criteria: Optional[str] = None
    project_name: Optional[str] = None
    assignee: Optional[str] = None


@dataclass
class FileContext:
    """File context for ownership suggestion."""

    file_path: str
    repository_path: str
    file_extension: str
    is_new_file: bool = False
    task_creator: Optional[str] = None


@dataclass
class PRContext:
    """PR context for context attachment and attestation."""

    pr_number: int
    pr_title: str
    pr_description: str
    changed_files: list[str] = field(default_factory=list)
    repository_path: str = ""
    author: Optional[str] = None


@dataclass
class AISessionContext:
    """AI session context for attestation generation."""

    session_id: str
    provider: str
    model: str
    generated_lines: int
    timestamp: datetime
    prompts: list[str] = field(default_factory=list)


# ============================================================================
# Generator 1: Intent Skeleton
# ============================================================================


class IntentGenerator:
    """
    Generate intent document from task description.

    Implements 3-level fallback:
    1. LLM (Ollama qwen3:32b) - Best quality
    2. Template - Deterministic
    3. Minimal - Basic structure

    Target Latency: <10s
    Time Saved: ~15 minutes per task
    """

    def __init__(self, ollama_service: Optional[OllamaService] = None):
        """
        Initialize intent generator.

        Args:
            ollama_service: Ollama service for LLM generation
        """
        self.ollama = ollama_service or get_ollama_service()
        self.llm_timeout = 10
        self.llm_model = "qwen3:32b"

    async def generate(self, task: TaskContext) -> GenerationResult:
        """
        Generate intent document for a task.

        Args:
            task: Task context with title, description, acceptance criteria

        Returns:
            GenerationResult with intent document content
        """
        start_time = time.time()

        # Try Level 1: LLM Generation
        try:
            if self.ollama.is_available:
                result = await self._generate_with_llm(task)
                if result.success:
                    result.latency_ms = (time.time() - start_time) * 1000
                    return result
        except Exception as e:
            logger.warning(f"Intent LLM generation failed: {e}")

        # Try Level 2: Template Generation
        try:
            result = self._generate_with_template(task)
            result.latency_ms = (time.time() - start_time) * 1000
            return result
        except Exception as e:
            logger.warning(f"Intent template generation failed: {e}")

        # Level 3: Minimal Fallback (always succeeds)
        result = self._generate_minimal(task)
        result.latency_ms = (time.time() - start_time) * 1000
        return result

    async def _generate_with_llm(self, task: TaskContext) -> GenerationResult:
        """Generate intent using Ollama LLM."""
        prompt = f"""Generate an intent document for this development task.

Task Title: {task.title}
Task Description: {task.description}
Acceptance Criteria: {task.acceptance_criteria or 'Not specified'}
Project: {task.project_name or 'Unknown'}

Create a structured intent document with these exact sections:

# Intent: [Title based on task]

## Why This Change?
[1-2 sentences explaining the business reason, not technical details]

## What Problem Does It Solve?
[2-3 bullet points describing user pain points or system issues]

## Alternatives Considered
[2-3 alternatives that were considered and rejected, with brief reasons]

Output only the markdown content, no additional commentary."""

        try:
            response = self.ollama.generate(
                prompt=prompt,
                model=self.llm_model,
                temperature=0.3,
                max_tokens=1500,
            )

            content = response.response.strip()

            # Validate the response has expected structure
            if "## Why This Change?" in content and "## What Problem" in content:
                return GenerationResult(
                    success=True,
                    fallback_level=FallbackLevel.LLM,
                    content=content,
                    confidence=85,
                    latency_ms=response.total_duration_ms,
                    generator_type=GeneratorType.INTENT,
                    metadata={
                        "model": response.model,
                        "tokens": response.eval_count,
                        "task_id": task.task_id,
                    },
                )

            # LLM response doesn't have expected structure
            logger.warning("LLM response missing expected sections, falling back")
            raise ValueError("LLM response missing expected sections")

        except (OllamaError, ValueError) as e:
            logger.warning(f"LLM intent generation failed: {e}")
            raise

    def _generate_with_template(self, task: TaskContext) -> GenerationResult:
        """Generate intent using template substitution."""
        template = f"""# Intent: {task.title}

## Why This Change?
This change addresses the following requirement:
{task.description[:200]}{'...' if len(task.description) > 200 else ''}

## What Problem Does It Solve?
Based on the task description:
- Primary issue: {task.description.split('.')[0] if task.description else 'Not specified'}
- Impact: Users/system affected by this issue
- Priority: Determined by business requirements

## Alternatives Considered
1. **Do Nothing** - Not viable because the issue impacts operations
2. **Manual Workaround** - Not scalable for production use
3. **This Implementation** - Chosen for balance of effort and impact

---
*Generated from template. Please review and enhance with specific details.*
"""
        return GenerationResult(
            success=True,
            fallback_level=FallbackLevel.TEMPLATE,
            content=template,
            confidence=60,
            latency_ms=0,
            generator_type=GeneratorType.INTENT,
            metadata={"task_id": task.task_id, "source": "template"},
        )

    def _generate_minimal(self, task: TaskContext) -> GenerationResult:
        """Generate minimal intent placeholder."""
        minimal = f"""# Intent: {task.title}

## Why This Change?
[Auto-generation failed. Please document the business reason.]

## What Problem Does It Solve?
{task.description or '[Please describe the problem]'}

## Alternatives Considered
[Please document alternatives you considered.]

---
*Auto-generation failed. Manual input required.*
"""
        return GenerationResult(
            success=True,
            fallback_level=FallbackLevel.MINIMAL,
            content=minimal,
            confidence=30,
            latency_ms=0,
            generator_type=GeneratorType.INTENT,
            metadata={"task_id": task.task_id, "source": "minimal_fallback"},
        )


# ============================================================================
# Generator 2: Ownership Suggestion
# ============================================================================


class OwnershipGenerator:
    """
    Suggest file ownership based on multiple sources.

    Algorithm (priority order):
    1. CODEOWNERS file (confidence: 1.0)
    2. Directory patterns (confidence: 0.9)
    3. Git blame (confidence: 0.7)
    4. Task creator (confidence: 0.5)
    5. Extension fallback (confidence: 0.3)

    Target Latency: <2s
    Time Saved: ~2 minutes per file
    """

    DIRECTORY_PATTERNS = {
        "backend/app/services/": ("@backend-team", "services"),
        "backend/app/api/": ("@backend-team", "api"),
        "backend/app/models/": ("@backend-team", "models"),
        "backend/app/services/governance/": ("@governance-team", "governance"),
        "frontend/src/components/": ("@frontend-team", "components"),
        "frontend/src/pages/": ("@frontend-team", "pages"),
        "frontend/src/app/": ("@frontend-team", "app"),
        "docs/": ("@documentation-team", "documentation"),
        "tests/": ("@qa-team", "testing"),
    }

    EXTENSION_FALLBACKS = {
        ".py": "@backend-team",
        ".ts": "@frontend-team",
        ".tsx": "@frontend-team",
        ".md": "@documentation-team",
        ".yaml": "@devops-team",
        ".yml": "@devops-team",
        ".sql": "@backend-team",
    }

    def __init__(self, repository_path: Optional[str] = None):
        """
        Initialize ownership generator.

        Args:
            repository_path: Path to repository root for git operations
        """
        self.repository_path = repository_path or "."

    async def generate(self, file: FileContext) -> GenerationResult:
        """
        Suggest ownership for a file.

        Args:
            file: File context with path and extension

        Returns:
            GenerationResult with ownership annotation
        """
        start_time = time.time()
        suggestions = []

        # Source 1: CODEOWNERS
        codeowners_owner = self._check_codeowners(file.file_path)
        if codeowners_owner:
            suggestions.append({
                "owner": codeowners_owner,
                "confidence": 1.0,
                "source": "CODEOWNERS",
            })

        # Source 2: Directory patterns
        pattern_result = self._check_directory_patterns(file.file_path)
        if pattern_result:
            suggestions.append({
                "owner": pattern_result[0],
                "module": pattern_result[1],
                "confidence": 0.9,
                "source": "directory_pattern",
            })

        # Source 3: Git blame (only for existing files)
        if not file.is_new_file:
            git_owner = await self._check_git_blame(file.file_path, file.repository_path)
            if git_owner:
                suggestions.append({
                    "owner": git_owner,
                    "confidence": 0.7,
                    "source": "git_blame",
                })

        # Source 4: Task creator
        if file.task_creator:
            suggestions.append({
                "owner": f"@{file.task_creator}",
                "confidence": 0.5,
                "source": "task_creator",
            })

        # Source 5: Extension fallback
        ext_owner = self.EXTENSION_FALLBACKS.get(file.file_extension)
        if ext_owner:
            suggestions.append({
                "owner": ext_owner,
                "confidence": 0.3,
                "source": "extension_fallback",
            })

        # Select best suggestion
        if not suggestions:
            return GenerationResult(
                success=True,
                fallback_level=FallbackLevel.MINIMAL,
                content=self._format_annotation(
                    owner="@team-lead",
                    module="unknown",
                    file_extension=file.file_extension,
                ),
                confidence=10,
                latency_ms=(time.time() - start_time) * 1000,
                generator_type=GeneratorType.OWNERSHIP,
                metadata={"file_path": file.file_path, "source": "default"},
            )

        # Pick highest confidence
        best = max(suggestions, key=lambda s: s["confidence"])

        # Determine module
        module = best.get("module")
        if not module:
            for pattern, (_, mod) in self.DIRECTORY_PATTERNS.items():
                if pattern in file.file_path:
                    module = mod
                    break
            if not module:
                module = Path(file.file_path).parent.name or "root"

        annotation = self._format_annotation(
            owner=best["owner"],
            module=module,
            file_extension=file.file_extension,
        )

        return GenerationResult(
            success=True,
            fallback_level=FallbackLevel.TEMPLATE,  # Ownership is always deterministic
            content=annotation,
            confidence=int(best["confidence"] * 100),
            latency_ms=(time.time() - start_time) * 1000,
            generator_type=GeneratorType.OWNERSHIP,
            metadata={
                "file_path": file.file_path,
                "owner": best["owner"],
                "module": module,
                "source": best["source"],
                "all_suggestions": suggestions,
            },
        )

    def _check_codeowners(self, file_path: str) -> Optional[str]:
        """Check CODEOWNERS file for ownership."""
        codeowners_paths = [
            Path(self.repository_path) / "CODEOWNERS",
            Path(self.repository_path) / ".github" / "CODEOWNERS",
            Path(self.repository_path) / "docs" / "CODEOWNERS",
        ]

        for codeowners_path in codeowners_paths:
            if codeowners_path.exists():
                try:
                    content = codeowners_path.read_text()
                    for line in content.strip().split("\n"):
                        line = line.strip()
                        if line and not line.startswith("#"):
                            parts = line.split()
                            if len(parts) >= 2:
                                pattern, owner = parts[0], parts[1]
                                if self._matches_pattern(file_path, pattern):
                                    return owner
                except Exception as e:
                    logger.warning(f"Error reading CODEOWNERS: {e}")

        return None

    def _matches_pattern(self, file_path: str, pattern: str) -> bool:
        """Check if file path matches CODEOWNERS pattern."""
        # Simple pattern matching (can be enhanced with fnmatch)
        if pattern.endswith("*"):
            return file_path.startswith(pattern[:-1])
        return file_path == pattern or file_path.endswith(pattern)

    def _check_directory_patterns(
        self, file_path: str
    ) -> Optional[tuple[str, str]]:
        """Check directory patterns for ownership."""
        for pattern, (owner, module) in self.DIRECTORY_PATTERNS.items():
            if pattern in file_path:
                return (owner, module)
        return None

    async def _check_git_blame(
        self, file_path: str, repo_path: str
    ) -> Optional[str]:
        """Get most frequent committer from git blame."""
        try:
            # Run git blame to get committers
            result = subprocess.run(
                ["git", "log", "--format=%an", "-n", "20", "--", file_path],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=5,
            )

            if result.returncode == 0 and result.stdout.strip():
                committers = result.stdout.strip().split("\n")
                # Get most frequent
                from collections import Counter

                counts = Counter(committers)
                most_common = counts.most_common(1)
                if most_common:
                    return f"@{most_common[0][0].replace(' ', '-').lower()}"

        except Exception as e:
            logger.debug(f"Git blame failed for {file_path}: {e}")

        return None

    def _format_annotation(
        self, owner: str, module: str, file_extension: str
    ) -> str:
        """Format ownership annotation based on file type."""
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        if file_extension in [".py"]:
            return f"""# @owner: {owner}
# @module: {module}
# @created: {date}
"""
        elif file_extension in [".ts", ".tsx", ".js", ".jsx"]:
            return f"""/**
 * @owner {owner}
 * @module {module}
 * @created {date}
 */
"""
        elif file_extension in [".yaml", ".yml"]:
            return f"""# @owner: {owner}
# @module: {module}
# @created: {date}
"""
        else:
            # Default format
            return f"""# @owner: {owner}
# @module: {module}
# @created: {date}
"""


# ============================================================================
# Generator 3: Context Attachment
# ============================================================================


class ContextAttachmentGenerator:
    """
    Auto-attach ADRs, specs, and design docs to PR description.

    Algorithm:
    1. Extract modules from changed files
    2. Find ADRs mentioning those modules
    3. Find specs in related directories
    4. Format context section for PR

    Target Latency: <5s
    Time Saved: ~5 minutes per PR
    """

    def __init__(self, repository_path: Optional[str] = None):
        """
        Initialize context attachment generator.

        Args:
            repository_path: Path to repository root
        """
        self.repository_path = repository_path or "."
        self.adr_paths = [
            "docs/02-design/03-ADRs",
            "docs/adr",
            "adr",
        ]
        self.spec_paths = [
            "docs/02-design/specs",
            "docs/01-planning/specs",
            "specs",
        ]

    async def generate(self, pr: PRContext) -> GenerationResult:
        """
        Generate context attachment for a PR.

        Args:
            pr: PR context with changed files

        Returns:
            GenerationResult with context section markdown
        """
        start_time = time.time()

        # Step 1: Extract modules from changed files
        modules = self._extract_modules(pr.changed_files)

        # Step 2: Find relevant ADRs
        adrs = await self._find_relevant_adrs(modules)

        # Step 3: Find relevant specs
        specs = await self._find_relevant_specs(modules)

        # Step 4: Format context section
        context_section = self._format_context_section(
            modules=modules,
            adrs=adrs,
            specs=specs,
            pr_number=pr.pr_number,
        )

        return GenerationResult(
            success=True,
            fallback_level=FallbackLevel.TEMPLATE,  # Always deterministic
            content=context_section,
            confidence=75 if (adrs or specs) else 50,
            latency_ms=(time.time() - start_time) * 1000,
            generator_type=GeneratorType.CONTEXT,
            metadata={
                "pr_number": pr.pr_number,
                "modules": modules,
                "adrs_found": len(adrs),
                "specs_found": len(specs),
            },
        )

    def _extract_modules(self, changed_files: list[str]) -> list[str]:
        """Extract module names from changed file paths."""
        modules = set()

        module_patterns = [
            # backend/app/services/{module}/*.py
            (r"backend/app/services/([^/]+)/", 1),
            # backend/app/api/routes/{module}.py
            (r"backend/app/api/routes/([^/]+)\.py", 1),
            # backend/app/models/{module}.py
            (r"backend/app/models/([^/]+)\.py", 1),
            # frontend/src/components/{module}/
            (r"frontend/src/components/([^/]+)/", 1),
            # frontend/src/app/{module}/
            (r"frontend/src/app/([^/]+)/", 1),
        ]

        import re

        for file_path in changed_files:
            for pattern, group in module_patterns:
                match = re.search(pattern, file_path)
                if match:
                    module = match.group(group)
                    if module not in ["__init__", "__pycache__"]:
                        modules.add(module)

            # Also add parent directory as module
            parts = Path(file_path).parts
            if len(parts) >= 2:
                modules.add(parts[-2])

        return list(modules)[:10]  # Limit to 10 modules

    async def _find_relevant_adrs(
        self, modules: list[str]
    ) -> list[dict[str, str]]:
        """Find ADRs that mention the given modules."""
        adrs = []

        for adr_base in self.adr_paths:
            adr_path = Path(self.repository_path) / adr_base
            if not adr_path.exists():
                continue

            for adr_file in adr_path.glob("*.md"):
                try:
                    content = adr_file.read_text()
                    title = self._extract_title(content)

                    # Check if ADR mentions any module
                    content_lower = content.lower()
                    for module in modules:
                        if module.lower() in content_lower:
                            adrs.append({
                                "file": str(adr_file.relative_to(self.repository_path)),
                                "title": title,
                                "module_match": module,
                            })
                            break

                except Exception as e:
                    logger.debug(f"Error reading ADR {adr_file}: {e}")

        return adrs[:5]  # Limit to 5 ADRs

    async def _find_relevant_specs(
        self, modules: list[str]
    ) -> list[dict[str, str]]:
        """Find specs related to the given modules."""
        specs = []

        for spec_base in self.spec_paths:
            spec_path = Path(self.repository_path) / spec_base
            if not spec_path.exists():
                continue

            for spec_file in spec_path.glob("*.md"):
                try:
                    content = spec_file.read_text()
                    title = self._extract_title(content)
                    filename = spec_file.stem.lower()

                    # Check if spec matches any module
                    for module in modules:
                        if module.lower() in filename or module.lower() in content.lower():
                            specs.append({
                                "file": str(spec_file.relative_to(self.repository_path)),
                                "title": title,
                                "module_match": module,
                            })
                            break

                except Exception as e:
                    logger.debug(f"Error reading spec {spec_file}: {e}")

        return specs[:5]  # Limit to 5 specs

    def _extract_title(self, content: str) -> str:
        """Extract title from markdown content."""
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("# "):
                return line[2:].strip()
        return "Untitled"

    def _format_context_section(
        self,
        modules: list[str],
        adrs: list[dict[str, str]],
        specs: list[dict[str, str]],
        pr_number: int,
    ) -> str:
        """Format context section for PR description."""
        sections = ["## Related Context (Auto-Generated)", ""]

        # ADRs section
        sections.append("### Architecture Decisions")
        if adrs:
            for adr in adrs:
                sections.append(f"- [{adr['title']}]({adr['file']})")
        else:
            sections.append("- *No related ADRs found*")
        sections.append("")

        # Specs section
        sections.append("### Design Specs")
        if specs:
            for spec in specs:
                sections.append(f"- [{spec['title']}]({spec['file']})")
        else:
            sections.append("- *No related specs found*")
        sections.append("")

        # Modules section
        sections.append("### Affected Modules")
        if modules:
            sections.append(f"- {', '.join(modules)}")
        else:
            sections.append("- *No modules detected*")
        sections.append("")

        sections.append("---")
        sections.append("*Context attached by SDLC Orchestrator Auto-Generation Layer*")

        return "\n".join(sections)


# ============================================================================
# Generator 4: Attestation Template
# ============================================================================


class AttestationGenerator:
    """
    Pre-fill AI attestation form with session data.

    Auto-fills 80%:
    - AI provider, model, session ID
    - Prompt hash, generated lines, timestamp

    Developer confirms 20%:
    - Review time (minimum 2 sec/line)
    - Modifications made
    - Understanding confirmation

    Target Latency: <3s
    Time Saved: ~8 minutes per AI session
    """

    def __init__(self):
        """Initialize attestation generator."""
        pass

    async def generate(
        self,
        pr: PRContext,
        ai_session: AISessionContext,
    ) -> GenerationResult:
        """
        Generate attestation template for AI-generated code.

        Args:
            pr: PR context
            ai_session: AI session context with provider, model, etc.

        Returns:
            GenerationResult with attestation markdown
        """
        start_time = time.time()

        # Calculate minimum review time (2 seconds per line)
        min_review_minutes = (ai_session.generated_lines * 2) / 60

        # Generate prompt hash for audit trail
        prompt_hash = self._hash_prompts(ai_session.prompts)

        # Format attestation
        attestation = self._format_attestation(
            pr_number=pr.pr_number,
            ai_provider=ai_session.provider,
            model=ai_session.model,
            session_id=ai_session.session_id,
            generated_lines=ai_session.generated_lines,
            timestamp=ai_session.timestamp,
            prompt_hash=prompt_hash,
            min_review_time=min_review_minutes,
            author=pr.author,
        )

        return GenerationResult(
            success=True,
            fallback_level=FallbackLevel.TEMPLATE,
            content=attestation,
            confidence=80,  # High confidence as this is data extraction
            latency_ms=(time.time() - start_time) * 1000,
            generator_type=GeneratorType.ATTESTATION,
            metadata={
                "pr_number": pr.pr_number,
                "session_id": ai_session.session_id,
                "generated_lines": ai_session.generated_lines,
                "min_review_time_minutes": min_review_minutes,
                "prompt_hash": prompt_hash,
            },
        )

    def _hash_prompts(self, prompts: list[str]) -> str:
        """Generate SHA256 hash of prompts for audit trail."""
        combined = "\n---\n".join(prompts)
        return hashlib.sha256(combined.encode()).hexdigest()[:16]

    def _format_attestation(
        self,
        pr_number: int,
        ai_provider: str,
        model: str,
        session_id: str,
        generated_lines: int,
        timestamp: datetime,
        prompt_hash: str,
        min_review_time: float,
        author: Optional[str],
    ) -> str:
        """Format attestation document."""
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        timestamp_str = timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")

        return f"""# AI Code Attestation - PR #{pr_number}

## AI Session Metadata (Auto-Generated)
- **AI Provider**: {ai_provider}
- **Model**: {model}
- **Session ID**: {session_id}
- **Generated Lines**: {generated_lines}
- **Timestamp**: {timestamp_str}
- **Prompt Hash**: {prompt_hash}

## Human Review (REQUIRED)

### Review Time
- **Minimum Required**: {min_review_time:.1f} minutes ({generated_lines} lines x 2 seconds/line)
- **Actual Review Time**: _____ minutes

### Modifications Made
Please check all that apply:
- [ ] Refactored code structure
- [ ] Added error handling
- [ ] Fixed type hints
- [ ] Added input validation
- [ ] Improved naming/readability
- [ ] Removed unused code
- [ ] Added comments/documentation
- [ ] Other: _____

### Understanding Confirmation
I have reviewed all AI-generated code and understand:
- [ ] The algorithm/logic used
- [ ] Edge cases handled
- [ ] Error conditions
- [ ] Performance characteristics
- [ ] Security implications

## Attestation Statement

I, **{author or '________________'}**, attest that:

1. I have thoroughly reviewed all AI-generated code in this PR
2. I spent at least {min_review_time:.1f} minutes reviewing the code
3. I made modifications where necessary to ensure quality
4. I understand the code and take responsibility for its correctness
5. I am aware of potential AI hallucinations and have verified critical logic

**Signed**: {author or '________________'}
**Date**: {date}

---
*Attestation template generated by SDLC Orchestrator Auto-Generation Layer*
*80% auto-filled from AI session data, 20% requires human input*
"""


# ============================================================================
# Main Auto-Generation Service
# ============================================================================


class AutoGenerationService:
    """
    Orchestrates all 4 compliance artifact generators.

    CORE PRINCIPLE:
    "GOVERNANCE MUST BE THE FASTEST WAY"
    Target: <5 minutes per PR (80% faster than 30 min baseline)

    Generators:
    1. IntentGenerator: Task description -> Intent document
    2. OwnershipGenerator: File path -> @owner annotation
    3. ContextAttachmentGenerator: Changed files -> ADR/spec links
    4. AttestationGenerator: AI session -> Attestation template

    Fail-Safe Chain:
    LLM -> Template -> Minimal Placeholder
    Guarantee: Developer can proceed within 2 minutes
    """

    def __init__(
        self,
        ollama_service: Optional[OllamaService] = None,
        repository_path: Optional[str] = None,
    ):
        """
        Initialize auto-generation service.

        Args:
            ollama_service: Ollama service for LLM generation
            repository_path: Path to repository root
        """
        self.ollama = ollama_service or get_ollama_service()
        self.repository_path = repository_path or "."

        # Initialize generators
        self.intent_generator = IntentGenerator(self.ollama)
        self.ownership_generator = OwnershipGenerator(self.repository_path)
        self.context_generator = ContextAttachmentGenerator(self.repository_path)
        self.attestation_generator = AttestationGenerator()

        logger.info("AutoGenerationService initialized")

    async def generate_intent(self, task: TaskContext) -> GenerationResult:
        """
        Generate intent document for a task.

        Args:
            task: Task context

        Returns:
            GenerationResult with intent markdown
        """
        logger.info(f"Generating intent for task: {task.task_id}")
        result = await self.intent_generator.generate(task)
        logger.info(
            f"Intent generated: level={result.fallback_level.value}, "
            f"confidence={result.confidence}, latency={result.latency_ms:.0f}ms"
        )
        return result

    async def suggest_ownership(self, file: FileContext) -> GenerationResult:
        """
        Suggest ownership for a file.

        Args:
            file: File context

        Returns:
            GenerationResult with ownership annotation
        """
        logger.info(f"Suggesting ownership for file: {file.file_path}")
        result = await self.ownership_generator.generate(file)
        logger.info(
            f"Ownership suggested: owner={result.metadata.get('owner')}, "
            f"confidence={result.confidence}, latency={result.latency_ms:.0f}ms"
        )
        return result

    async def attach_context(self, pr: PRContext) -> GenerationResult:
        """
        Attach context (ADRs, specs) to PR.

        Args:
            pr: PR context

        Returns:
            GenerationResult with context section markdown
        """
        logger.info(f"Attaching context for PR: #{pr.pr_number}")
        result = await self.context_generator.generate(pr)
        logger.info(
            f"Context attached: adrs={result.metadata.get('adrs_found')}, "
            f"specs={result.metadata.get('specs_found')}, latency={result.latency_ms:.0f}ms"
        )
        return result

    async def generate_attestation(
        self,
        pr: PRContext,
        ai_session: AISessionContext,
    ) -> GenerationResult:
        """
        Generate attestation template for AI-generated code.

        Args:
            pr: PR context
            ai_session: AI session context

        Returns:
            GenerationResult with attestation markdown
        """
        logger.info(f"Generating attestation for PR: #{pr.pr_number}")
        result = await self.attestation_generator.generate(pr, ai_session)
        logger.info(
            f"Attestation generated: lines={ai_session.generated_lines}, "
            f"min_review={result.metadata.get('min_review_time_minutes'):.1f}min, "
            f"latency={result.latency_ms:.0f}ms"
        )
        return result

    async def generate_all_for_pr(
        self,
        pr: PRContext,
        task: Optional[TaskContext] = None,
        ai_session: Optional[AISessionContext] = None,
    ) -> dict[str, GenerationResult]:
        """
        Generate all applicable compliance artifacts for a PR.

        Args:
            pr: PR context
            task: Optional task context for intent generation
            ai_session: Optional AI session for attestation

        Returns:
            Dict mapping generator type to result
        """
        results = {}

        # Always generate context attachment
        results["context"] = await self.attach_context(pr)

        # Generate intent if task provided
        if task:
            results["intent"] = await self.generate_intent(task)

        # Generate ownership for changed files
        ownership_results = []
        for file_path in pr.changed_files[:5]:  # Limit to 5 files
            ext = Path(file_path).suffix
            file = FileContext(
                file_path=file_path,
                repository_path=pr.repository_path,
                file_extension=ext,
                is_new_file=False,
            )
            ownership_results.append(await self.suggest_ownership(file))
        results["ownership"] = ownership_results

        # Generate attestation if AI session provided
        if ai_session:
            results["attestation"] = await self.generate_attestation(pr, ai_session)

        return results

    def health_check(self) -> dict[str, Any]:
        """
        Check health of auto-generation service.

        Returns:
            Health status dict
        """
        ollama_health = self.ollama.health_check()

        return {
            "service": "AutoGenerationService",
            "healthy": True,
            "ollama_available": ollama_health.get("healthy", False),
            "ollama_models": ollama_health.get("models", []),
            "generators": {
                "intent": "enabled",
                "ownership": "enabled",
                "context": "enabled",
                "attestation": "enabled",
            },
            "fail_safe_enabled": True,
            "target_latency": "<5s per generator",
        }


# ============================================================================
# Factory Functions
# ============================================================================


def create_auto_generation_service(
    ollama_service: Optional[OllamaService] = None,
    repository_path: Optional[str] = None,
) -> AutoGenerationService:
    """
    Factory function to create AutoGenerationService instance.

    Args:
        ollama_service: Ollama service for LLM generation
        repository_path: Path to repository root

    Returns:
        AutoGenerationService instance
    """
    return AutoGenerationService(
        ollama_service=ollama_service,
        repository_path=repository_path,
    )


# Global instance (lazy initialization)
_auto_generation_service: Optional[AutoGenerationService] = None


def get_auto_generation_service() -> AutoGenerationService:
    """
    Get global AutoGenerationService instance (singleton pattern).

    Returns:
        AutoGenerationService instance
    """
    global _auto_generation_service
    if _auto_generation_service is None:
        _auto_generation_service = create_auto_generation_service()
    return _auto_generation_service
