"""
Commit Message Detector - AI Detection Strategy

SDLC Stage: 04 - BUILD
Sprint: 42 - AI Detection & Validation Pipeline
Framework: SDLC 5.1.1

Purpose:
Detect AI tools from commit message patterns.
Uses regex pattern matching for AI tool signatures.

Detection Approach:
- Regex patterns for co-authored-by, generated-by tags
- Tool-specific commit message conventions
- Higher confidence than metadata (0.9 vs 0.8)

Patterns Detected:
- GitHub Copilot: "co-authored-by: GitHub Copilot"
- Cursor: "Generated by Cursor", "[cursor]"
- Claude Code: "Generated with Claude Code"
"""

import re
from typing import Dict, List

from . import AIDetectionStrategy, AIToolType, DetectionMethod, DetectionResult


class CommitDetector(AIDetectionStrategy):
    """Detect AI tools from commit message patterns."""

    # Commit message patterns (regex)
    COMMIT_PATTERNS: Dict[AIToolType, List[str]] = {
        AIToolType.COPILOT: [
            r"co-authored-by:.*copilot",
            r"generated\s+by\s+copilot",
            r"\[copilot\]",
            r"github\s+copilot",
        ],
        AIToolType.CURSOR: [
            r"generated\s+by\s+cursor",
            r"\[cursor\]",
            r"cursor\.sh",
            r"cursor\s+ai",
        ],
        AIToolType.CLAUDE_CODE: [
            r"generated\s+with\s+claude",
            r"claude\s+code",
            r"\[claude\]",
            r"anthropic\s+claude",
        ],
        AIToolType.CHATGPT: [
            r"generated\s+by\s+chatgpt",
            r"\[chatgpt\]",
            r"openai\s+gpt",
            r"gpt-4\s+generated",
        ],
        AIToolType.WINDSURF: [
            r"generated\s+by\s+windsurf",
            r"\[windsurf\]",
        ],
        AIToolType.CODY: [
            r"generated\s+by\s+cody",
            r"\[cody\]",
            r"sourcegraph\s+cody",
        ],
        AIToolType.TABNINE: [
            r"generated\s+by\s+tabnine",
            r"\[tabnine\]",
        ],
    }

    async def detect(
        self,
        pr_data: dict,
        commits: List[dict],
        diff: str,
    ) -> DetectionResult:
        """
        Detect AI tool from commit message patterns.

        High Confidence: 0.9 (explicit markers in commits)
        Scans all commit messages for AI tool signatures.

        Args:
            pr_data: PR data (not used by this detector)
            commits: List of commit objects
            diff: Unified diff (not used by this detector)

        Returns:
            DetectionResult with confidence 0.9 if pattern found
        """
        for commit in commits:
            msg = (commit.get("commit", {}).get("message") or "").lower()

            for tool, patterns in self.COMMIT_PATTERNS.items():
                for pattern in patterns:
                    match = re.search(pattern, msg, re.IGNORECASE)
                    if match:
                        return DetectionResult(
                            detected=True,
                            confidence=0.9,  # High confidence (explicit marker)
                            tool=tool,
                            method=DetectionMethod.COMMIT_MESSAGE,
                            evidence={
                                "commit_sha": commit.get("sha"),
                                "matched_pattern": pattern,
                                "matched_text": match.group(0),
                                "commit_message_preview": msg[:200],
                            },
                        )

        # No commit pattern found
        return DetectionResult(
            detected=False,
            confidence=0.0,
            tool=None,
            method=DetectionMethod.COMMIT_MESSAGE,
            evidence={"scanned_commits": len(commits)},
        )

    def get_strategy_name(self) -> str:
        return "commit_message"
