# =========================================================================
# STATUS: FROZEN (Sprint 173, Feb 2026)
# TIER: Enterprise
# REASON: Non-core for current phase. Working code preserved.
# REACTIVATION: CPO approval required.
# DO NOT: Delete, refactor, or add features without CTO approval.
# =========================================================================
"""
=========================================================================
SASE AI Generation Service - AI-Assisted Artifact Generation
SDLC Orchestrator - Sprint 151 (SASE Artifacts Enhancement)

Version: 1.0.0
Date: February 3, 2026
Status: ACTIVE - Day 4 Implementation
Authority: CTO Approved
Framework: SDLC 6.0.5 SASE Methodology
Reference: SPEC-0024, ADR-048

Purpose:
AI-assisted generation for SASE artifacts:
- VCR (Version Controlled Resolution): Generate from PR context
- CRP (Consultation Request Protocol): Generate from development context

AI Integration:
- Primary: Ollama (qwen3-coder:30b for code analysis)
- Fallback: Rule-based templates if AI unavailable
- Context-aware: Uses PR diff, commit messages, code snippets

Features:
- PR diff analysis for VCR generation
- AI tool detection (Cursor, Claude Code, Copilot markers)
- Problem/solution extraction from commit messages
- Code snippet analysis for CRP questions
- Confidence scoring for generated content

Performance Targets:
- VCR generation: <5s (with AI), <100ms (rule-based)
- CRP generation: <3s (with AI), <50ms (rule-based)

Zero Mock Policy: Production-ready implementation
=========================================================================
"""

import json
import logging
import re
import time
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID

from app.core.config import settings
from app.services.ollama_service import OllamaService, OllamaModel, OllamaError, create_ollama_service

logger = logging.getLogger(__name__)


# =============================================================================
# AI Tool Detection
# =============================================================================


class AIToolType(str, Enum):
    """Detected AI coding tools."""
    CURSOR = "cursor"
    CLAUDE_CODE = "claude_code"
    COPILOT = "copilot"
    CODEIUM = "codeium"
    TABNINE = "tabnine"
    CHATGPT = "chatgpt"
    GEMINI = "gemini"
    UNKNOWN = "unknown"


# AI tool markers in code and commits
AI_TOOL_MARKERS = {
    AIToolType.CURSOR: [
        "cursor-generated",
        "cursor ai",
        "@cursor",
        "// cursor",
        "# cursor",
        "cursor.sh",
        "generated by cursor",
    ],
    AIToolType.CLAUDE_CODE: [
        "claude",
        "anthropic",
        "claude-code",
        "// claude",
        "# claude",
        "generated by claude",
        "co-authored-by: claude",
    ],
    AIToolType.COPILOT: [
        "copilot",
        "github copilot",
        "// copilot",
        "# copilot",
        "generated by copilot",
        "copilot suggestion",
    ],
    AIToolType.CODEIUM: [
        "codeium",
        "// codeium",
        "# codeium",
    ],
    AIToolType.TABNINE: [
        "tabnine",
        "// tabnine",
        "# tabnine",
    ],
    AIToolType.CHATGPT: [
        "chatgpt",
        "openai",
        "gpt-4",
        "gpt-3",
        "// gpt",
        "# gpt",
    ],
    AIToolType.GEMINI: [
        "gemini",
        "google ai",
        "bard",
    ],
}


# =============================================================================
# Data Classes
# =============================================================================


@dataclass
class VCRGenerationResult:
    """Result of VCR AI generation."""
    title: str
    problem_statement: str
    root_cause_analysis: Optional[str]
    solution_approach: str
    implementation_notes: Optional[str]
    ai_tools_detected: list[str]
    ai_percentage_estimate: float
    confidence: float
    generation_time_ms: float
    provider_used: str
    fallback_used: bool = False


@dataclass
class CRPGenerationResult:
    """Result of CRP AI generation."""
    title: str
    question: str
    context: str
    options_considered: list[dict[str, str]]
    recommendation: Optional[str]
    impact_assessment: str
    required_expertise: list[str]
    priority_suggestion: str
    confidence: float
    generation_time_ms: float
    provider_used: str
    fallback_used: bool = False


# =============================================================================
# SASE AI Generation Service
# =============================================================================


class SASEGenerationService:
    """
    AI-assisted generation service for SASE artifacts.

    Provides intelligent content generation for:
    - VCR: From PR diffs, commits, and code changes
    - CRP: From development context and code snippets

    Usage:
        service = SASEGenerationService()

        # Generate VCR from PR
        vcr_result = await service.generate_vcr(
            pr_diff="--- a/file.py\n+++ b/file.py\n...",
            commit_messages=["fix: auth bug", "feat: add retry"],
            pr_title="Fix authentication timeout",
        )

        # Generate CRP from context
        crp_result = await service.generate_crp(
            context="Implementing auth with OAuth2 vs JWT",
            code_snippet="def authenticate(token)...",
        )
    """

    def __init__(
        self,
        ollama_service: Optional[OllamaService] = None,
    ):
        """
        Initialize SASE generation service.

        Args:
            ollama_service: Optional pre-configured Ollama service
        """
        self.ollama = ollama_service or create_ollama_service(
            base_url=settings.OLLAMA_URL,
            model=OllamaModel.QWEN3_CODER_30B.value,  # Best for code analysis
        )
        logger.info("SASE Generation Service initialized")

    # =========================================================================
    # VCR Generation
    # =========================================================================

    async def generate_vcr(
        self,
        pr_diff: Optional[str] = None,
        commit_messages: Optional[list[str]] = None,
        pr_title: Optional[str] = None,
        pr_description: Optional[str] = None,
        file_changes: Optional[list[dict[str, Any]]] = None,
        additional_context: Optional[str] = None,
    ) -> VCRGenerationResult:
        """
        Generate VCR content from PR context using AI.

        Args:
            pr_diff: Git diff content
            commit_messages: List of commit messages
            pr_title: PR title
            pr_description: PR description
            file_changes: List of changed files with stats
            additional_context: Any additional context

        Returns:
            VCRGenerationResult with generated content
        """
        start_time = time.time()

        # Detect AI tools from diff and commits
        ai_tools = self._detect_ai_tools(
            diff=pr_diff,
            commits=commit_messages,
            description=pr_description,
        )

        # Estimate AI percentage
        ai_percentage = self._estimate_ai_percentage(ai_tools, pr_diff)

        # Try AI generation first
        try:
            result = await self._generate_vcr_with_ai(
                pr_diff=pr_diff,
                commit_messages=commit_messages,
                pr_title=pr_title,
                pr_description=pr_description,
                file_changes=file_changes,
                additional_context=additional_context,
            )

            generation_time = (time.time() - start_time) * 1000

            return VCRGenerationResult(
                title=result.get("title", pr_title or "Untitled VCR"),
                problem_statement=result.get("problem_statement", ""),
                root_cause_analysis=result.get("root_cause_analysis"),
                solution_approach=result.get("solution_approach", ""),
                implementation_notes=result.get("implementation_notes"),
                ai_tools_detected=[t.value for t in ai_tools],
                ai_percentage_estimate=ai_percentage,
                confidence=result.get("confidence", 0.7),
                generation_time_ms=generation_time,
                provider_used="ollama",
                fallback_used=False,
            )

        except (OllamaError, Exception) as e:
            logger.warning(f"AI generation failed, using rule-based: {e}")

            # Fallback to rule-based generation
            return self._generate_vcr_rule_based(
                pr_diff=pr_diff,
                commit_messages=commit_messages,
                pr_title=pr_title,
                pr_description=pr_description,
                ai_tools=ai_tools,
                ai_percentage=ai_percentage,
                start_time=start_time,
            )

    async def _generate_vcr_with_ai(
        self,
        pr_diff: Optional[str],
        commit_messages: Optional[list[str]],
        pr_title: Optional[str],
        pr_description: Optional[str],
        file_changes: Optional[list[dict[str, Any]]],
        additional_context: Optional[str],
    ) -> dict[str, Any]:
        """Generate VCR using AI with structured prompt."""

        # Build context for AI
        context_parts = []

        if pr_title:
            context_parts.append(f"PR Title: {pr_title}")

        if pr_description:
            context_parts.append(f"PR Description:\n{pr_description[:2000]}")

        if commit_messages:
            commits_text = "\n".join(f"- {msg}" for msg in commit_messages[:20])
            context_parts.append(f"Commit Messages:\n{commits_text}")

        if file_changes:
            files_text = "\n".join(
                f"- {f.get('filename', 'unknown')}: +{f.get('additions', 0)}/-{f.get('deletions', 0)}"
                for f in file_changes[:30]
            )
            context_parts.append(f"Files Changed:\n{files_text}")

        if pr_diff:
            # Truncate diff to reasonable size
            diff_preview = pr_diff[:8000] if len(pr_diff) > 8000 else pr_diff
            context_parts.append(f"Code Diff (preview):\n```\n{diff_preview}\n```")

        if additional_context:
            context_parts.append(f"Additional Context:\n{additional_context}")

        context = "\n\n".join(context_parts)

        # Build prompt
        prompt = f"""You are an expert software documentation writer. Analyze the following PR changes and generate a VCR (Version Controlled Resolution) document.

{context}

Generate a JSON response with the following fields:
- title: A clear, concise title for this VCR (max 100 chars)
- problem_statement: What problem was being solved? (2-4 sentences)
- root_cause_analysis: What was the root cause? (optional, 1-3 sentences)
- solution_approach: How was the problem solved? (2-4 sentences)
- implementation_notes: Important notes for future developers (optional, 1-3 bullet points)
- confidence: Your confidence in this analysis (0.0 to 1.0)

Respond ONLY with valid JSON, no markdown formatting."""

        # Call Ollama
        response = await self.ollama.generate_async(
            prompt=prompt,
            system="You are a technical documentation expert. Always respond with valid JSON only.",
            options={"temperature": 0.3, "num_predict": 1000},
        )

        # Parse JSON response
        try:
            # Clean response - remove markdown if present
            text = response.text.strip()
            if text.startswith("```"):
                text = re.sub(r"```json?\n?", "", text)
                text = re.sub(r"```\n?$", "", text)

            return json.loads(text)
        except json.JSONDecodeError:
            # Try to extract fields with regex if JSON parse fails
            return {
                "title": pr_title or "PR Changes",
                "problem_statement": self._extract_section(response.text, "problem"),
                "solution_approach": self._extract_section(response.text, "solution"),
                "confidence": 0.5,
            }

    def _generate_vcr_rule_based(
        self,
        pr_diff: Optional[str],
        commit_messages: Optional[list[str]],
        pr_title: Optional[str],
        pr_description: Optional[str],
        ai_tools: list[AIToolType],
        ai_percentage: float,
        start_time: float,
    ) -> VCRGenerationResult:
        """Generate VCR using rule-based templates."""

        # Extract problem from commits
        problem = "This PR addresses the following changes:"
        if commit_messages:
            # Look for fix/bug commits
            fix_commits = [m for m in commit_messages if any(
                p in m.lower() for p in ["fix", "bug", "issue", "resolve", "patch"]
            )]
            if fix_commits:
                problem = f"Bug fix: {fix_commits[0]}"
            else:
                problem = f"Changes related to: {commit_messages[0]}"

        # Extract solution from commits
        solution = "The following approach was taken:"
        if commit_messages:
            feat_commits = [m for m in commit_messages if any(
                p in m.lower() for p in ["feat", "add", "implement", "create", "new"]
            )]
            if feat_commits:
                solution = f"Implementation: {feat_commits[0]}"
            elif pr_description:
                solution = pr_description[:500]

        # Count file changes
        files_changed = 0
        lines_added = 0
        lines_deleted = 0
        if pr_diff:
            files_changed = pr_diff.count("diff --git")
            lines_added = pr_diff.count("\n+") - pr_diff.count("\n+++")
            lines_deleted = pr_diff.count("\n-") - pr_diff.count("\n---")

        implementation_notes = (
            f"- {files_changed} files changed\n"
            f"- +{lines_added}/-{lines_deleted} lines\n"
            f"- AI tools used: {', '.join(t.value for t in ai_tools) or 'None detected'}"
        )

        generation_time = (time.time() - start_time) * 1000

        return VCRGenerationResult(
            title=pr_title or "PR Changes Summary",
            problem_statement=problem,
            root_cause_analysis=None,
            solution_approach=solution,
            implementation_notes=implementation_notes,
            ai_tools_detected=[t.value for t in ai_tools],
            ai_percentage_estimate=ai_percentage,
            confidence=0.3,  # Low confidence for rule-based
            generation_time_ms=generation_time,
            provider_used="rule_based",
            fallback_used=True,
        )

    # =========================================================================
    # CRP Generation
    # =========================================================================

    async def generate_crp(
        self,
        context: str,
        code_snippet: Optional[str] = None,
        related_files: Optional[list[str]] = None,
        project_tech_stack: Optional[list[str]] = None,
    ) -> CRPGenerationResult:
        """
        Generate CRP content from development context using AI.

        Args:
            context: Description of the situation needing consultation
            code_snippet: Relevant code snippet
            related_files: List of related file paths
            project_tech_stack: Project's technology stack

        Returns:
            CRPGenerationResult with generated content
        """
        start_time = time.time()

        # Try AI generation first
        try:
            result = await self._generate_crp_with_ai(
                context=context,
                code_snippet=code_snippet,
                related_files=related_files,
                project_tech_stack=project_tech_stack,
            )

            generation_time = (time.time() - start_time) * 1000

            return CRPGenerationResult(
                title=result.get("title", "Consultation Request"),
                question=result.get("question", context),
                context=result.get("context", ""),
                options_considered=result.get("options_considered", []),
                recommendation=result.get("recommendation"),
                impact_assessment=result.get("impact_assessment", ""),
                required_expertise=result.get("required_expertise", ["general"]),
                priority_suggestion=result.get("priority_suggestion", "medium"),
                confidence=result.get("confidence", 0.7),
                generation_time_ms=generation_time,
                provider_used="ollama",
                fallback_used=False,
            )

        except (OllamaError, Exception) as e:
            logger.warning(f"AI generation failed, using rule-based: {e}")

            return self._generate_crp_rule_based(
                context=context,
                code_snippet=code_snippet,
                related_files=related_files,
                start_time=start_time,
            )

    async def _generate_crp_with_ai(
        self,
        context: str,
        code_snippet: Optional[str],
        related_files: Optional[list[str]],
        project_tech_stack: Optional[list[str]],
    ) -> dict[str, Any]:
        """Generate CRP using AI with structured prompt."""

        # Build context
        context_parts = [f"Development Context:\n{context}"]

        if code_snippet:
            context_parts.append(f"Relevant Code:\n```\n{code_snippet[:3000]}\n```")

        if related_files:
            context_parts.append(f"Related Files:\n" + "\n".join(f"- {f}" for f in related_files[:10]))

        if project_tech_stack:
            context_parts.append(f"Tech Stack: {', '.join(project_tech_stack)}")

        full_context = "\n\n".join(context_parts)

        prompt = f"""You are an expert software consultant. Analyze the following development context and generate a CRP (Consultation Request Protocol) document.

{full_context}

Generate a JSON response with:
- title: A clear, concise title (max 80 chars)
- question: The specific question needing consultation
- context: Background information for the reviewer
- options_considered: Array of objects with "option" and "pros_cons" fields (2-3 options)
- recommendation: Your recommended approach (optional)
- impact_assessment: Impact of the decision on the project
- required_expertise: Array of expertise types needed (from: security, database, api, architecture, concurrency, general)
- priority_suggestion: Suggested priority (low, medium, high, urgent)
- confidence: Your confidence score (0.0 to 1.0)

Respond ONLY with valid JSON."""

        response = await self.ollama.generate_async(
            prompt=prompt,
            system="You are a technical consultant expert. Always respond with valid JSON only.",
            options={"temperature": 0.4, "num_predict": 1500},
        )

        # Parse JSON response
        try:
            text = response.text.strip()
            if text.startswith("```"):
                text = re.sub(r"```json?\n?", "", text)
                text = re.sub(r"```\n?$", "", text)

            return json.loads(text)
        except json.JSONDecodeError:
            return {
                "title": "Consultation Request",
                "question": context[:200],
                "context": context,
                "options_considered": [],
                "required_expertise": ["general"],
                "priority_suggestion": "medium",
                "confidence": 0.5,
            }

    def _generate_crp_rule_based(
        self,
        context: str,
        code_snippet: Optional[str],
        related_files: Optional[list[str]],
        start_time: float,
    ) -> CRPGenerationResult:
        """Generate CRP using rule-based templates."""

        # Detect expertise from context
        expertise = self._detect_required_expertise(context, code_snippet)

        # Detect priority from keywords
        priority = self._detect_priority(context)

        # Generate basic options
        options = [
            {
                "option": "Option A",
                "pros_cons": "Please describe the first approach considered.",
            },
            {
                "option": "Option B",
                "pros_cons": "Please describe the alternative approach.",
            },
        ]

        generation_time = (time.time() - start_time) * 1000

        return CRPGenerationResult(
            title="Consultation Request",
            question=context[:200] + "..." if len(context) > 200 else context,
            context=context,
            options_considered=options,
            recommendation=None,
            impact_assessment="Please assess the impact of this decision.",
            required_expertise=expertise,
            priority_suggestion=priority,
            confidence=0.3,
            generation_time_ms=generation_time,
            provider_used="rule_based",
            fallback_used=True,
        )

    # =========================================================================
    # Helper Methods
    # =========================================================================

    def _detect_ai_tools(
        self,
        diff: Optional[str] = None,
        commits: Optional[list[str]] = None,
        description: Optional[str] = None,
    ) -> list[AIToolType]:
        """Detect AI tools from various sources."""
        detected = set()

        # Combine all text sources
        text_sources = []
        if diff:
            text_sources.append(diff.lower())
        if commits:
            text_sources.append(" ".join(commits).lower())
        if description:
            text_sources.append(description.lower())

        combined_text = " ".join(text_sources)

        # Check for markers
        for tool, markers in AI_TOOL_MARKERS.items():
            for marker in markers:
                if marker.lower() in combined_text:
                    detected.add(tool)
                    break

        return list(detected)

    def _estimate_ai_percentage(
        self,
        ai_tools: list[AIToolType],
        diff: Optional[str],
    ) -> float:
        """Estimate percentage of AI-generated code."""
        if not ai_tools:
            return 0.0

        # Base estimate based on number of tools detected
        base = min(0.3 + (len(ai_tools) * 0.1), 0.7)

        # Adjust based on diff characteristics
        if diff:
            # Large uniform changes often indicate AI generation
            lines = diff.split("\n")
            addition_lines = [l for l in lines if l.startswith("+") and not l.startswith("+++")]

            if len(addition_lines) > 100:
                # Large additions suggest higher AI involvement
                base = min(base + 0.1, 0.8)

            # Check for documentation patterns (often AI-generated)
            doc_markers = ["docstring", "/**", "'''", '"""', "@param", "@return"]
            doc_count = sum(1 for marker in doc_markers if marker in diff.lower())
            if doc_count >= 2:
                base = min(base + 0.1, 0.85)

        return round(base, 2)

    def _detect_required_expertise(
        self,
        context: str,
        code_snippet: Optional[str],
    ) -> list[str]:
        """Detect required expertise from context."""
        expertise = []
        combined = (context + (code_snippet or "")).lower()

        expertise_keywords = {
            "security": ["auth", "security", "encryption", "token", "jwt", "oauth", "password", "credential", "vulnerability"],
            "database": ["database", "sql", "query", "migration", "schema", "index", "transaction", "orm"],
            "api": ["api", "endpoint", "rest", "graphql", "request", "response", "http", "route"],
            "architecture": ["architecture", "design", "pattern", "refactor", "module", "service", "layer"],
            "concurrency": ["async", "thread", "concurrent", "parallel", "race", "lock", "mutex", "queue"],
        }

        for exp, keywords in expertise_keywords.items():
            if any(kw in combined for kw in keywords):
                expertise.append(exp)

        return expertise if expertise else ["general"]

    def _detect_priority(self, context: str) -> str:
        """Detect priority from context."""
        context_lower = context.lower()

        urgent_keywords = ["urgent", "critical", "asap", "immediately", "blocking", "production", "down"]
        high_keywords = ["important", "priority", "deadline", "security", "customer", "release"]
        low_keywords = ["minor", "eventually", "nice to have", "low priority", "cleanup"]

        if any(kw in context_lower for kw in urgent_keywords):
            return "urgent"
        elif any(kw in context_lower for kw in high_keywords):
            return "high"
        elif any(kw in context_lower for kw in low_keywords):
            return "low"

        return "medium"

    def _extract_section(self, text: str, section: str) -> str:
        """Extract a section from AI response text."""
        # Try to find section in response
        patterns = [
            rf"{section}[:\s]+([^\n]+(?:\n[^\n]+)*)",
            rf"\"?{section}\"?[:\s]+\"?([^\"]+)\"?",
        ]

        for pattern in patterns:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                return match.group(1).strip()

        return f"Please provide {section} details."


# =============================================================================
# Factory Function
# =============================================================================


def create_sase_generation_service(
    ollama_service: Optional[OllamaService] = None,
) -> SASEGenerationService:
    """
    Factory function to create SASE generation service.

    Args:
        ollama_service: Optional pre-configured Ollama service

    Returns:
        Configured SASEGenerationService instance
    """
    return SASEGenerationService(ollama_service=ollama_service)
