"""
Unit tests for ProviderRegistry.

Sprint 45: Multi-Provider Codegen Architecture (EP-06)
Tests registry pattern with fallback chain.
"""

import pytest
from typing import Dict, Any

from app.services.codegen.base_provider import (
    CodegenSpec,
    CodegenResult,
    ValidationResult,
    CostEstimate,
    CodegenProvider,
)
from app.services.codegen.provider_registry import ProviderRegistry


class MockProvider(CodegenProvider):
    """Mock provider for testing."""

    def __init__(self, name: str = "mock", available: bool = True):
        self._name = name
        self._available = available

    @property
    def name(self) -> str:
        return self._name

    @property
    def is_available(self) -> bool:
        return self._available

    async def generate(self, spec: CodegenSpec) -> CodegenResult:
        return CodegenResult(
            code=f"# Generated by {self._name}",
            files={},
            metadata={},
            provider=self._name
        )

    async def validate(self, code: str, context: Dict[str, Any]) -> ValidationResult:
        return ValidationResult(valid=True, errors=[], warnings=[], suggestions=[])

    def estimate_cost(self, spec: CodegenSpec) -> CostEstimate:
        return CostEstimate(
            estimated_tokens=1000,
            estimated_cost_usd=0.001,
            provider=self._name
        )


class TestProviderRegistry:
    """Test ProviderRegistry functionality."""

    def test_register_provider(self):
        """Test registering a provider."""
        registry = ProviderRegistry()
        provider = MockProvider(name="test")

        registry.register(provider)

        assert "test" in registry.list_providers()

    def test_register_duplicate_replaces(self):
        """Test registering duplicate provider replaces existing."""
        registry = ProviderRegistry()
        provider1 = MockProvider(name="test", available=True)
        provider2 = MockProvider(name="test", available=False)

        registry.register(provider1)
        registry.register(provider2)

        providers = registry.list_providers()
        assert providers.count("test") == 1

    def test_get_provider(self):
        """Test getting a provider by name."""
        registry = ProviderRegistry()
        provider = MockProvider(name="ollama")
        registry.register(provider)

        result = registry.get("ollama")

        assert result is provider

    def test_get_nonexistent_provider(self):
        """Test getting nonexistent provider returns None."""
        registry = ProviderRegistry()

        result = registry.get("nonexistent")

        assert result is None

    def test_list_providers(self):
        """Test listing all provider names."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama"))
        registry.register(MockProvider(name="claude"))
        registry.register(MockProvider(name="deepcode"))

        providers = registry.list_providers()

        assert len(providers) == 3
        assert "ollama" in providers
        assert "claude" in providers
        assert "deepcode" in providers

    def test_list_available_providers(self):
        """Test listing only available providers."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.register(MockProvider(name="claude", available=False))
        registry.register(MockProvider(name="deepcode", available=True))

        available = registry.list_available()

        assert len(available) == 2
        assert "ollama" in available
        assert "deepcode" in available
        assert "claude" not in available


class TestFallbackChain:
    """Test fallback chain functionality."""

    def test_default_fallback_chain(self):
        """Test default fallback chain order."""
        registry = ProviderRegistry()

        chain = registry.get_fallback_chain()

        assert chain == ["ollama", "claude", "deepcode"]

    def test_set_fallback_chain(self):
        """Test setting custom fallback chain."""
        registry = ProviderRegistry()

        registry.set_fallback_chain(["claude", "ollama", "deepcode"])
        chain = registry.get_fallback_chain()

        assert chain == ["claude", "ollama", "deepcode"]

    def test_select_provider_preferred(self):
        """Test selecting preferred provider."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.register(MockProvider(name="claude", available=True))

        provider = registry.select_provider(preferred="claude")

        assert provider is not None
        assert provider.name == "claude"

    def test_select_provider_fallback(self):
        """Test fallback when preferred unavailable."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.register(MockProvider(name="claude", available=False))

        provider = registry.select_provider(preferred="claude")

        assert provider is not None
        assert provider.name == "ollama"

    def test_select_provider_no_preferred(self):
        """Test selecting without preference uses fallback chain."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.register(MockProvider(name="claude", available=True))
        registry.set_fallback_chain(["ollama", "claude"])

        provider = registry.select_provider()

        assert provider is not None
        assert provider.name == "ollama"

    def test_select_provider_none_available(self):
        """Test returns None when no providers available."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=False))
        registry.register(MockProvider(name="claude", available=False))

        provider = registry.select_provider()

        assert provider is None

    def test_select_provider_skips_unavailable(self):
        """Test skips unavailable providers in chain."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=False))
        registry.register(MockProvider(name="claude", available=False))
        registry.register(MockProvider(name="deepcode", available=True))

        provider = registry.select_provider()

        assert provider is not None
        assert provider.name == "deepcode"


class TestProviderInfo:
    """Test provider info retrieval."""

    def test_get_provider_info(self):
        """Test getting detailed provider info."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.set_fallback_chain(["ollama", "claude"])

        info = registry.get_provider_info("ollama")

        assert info is not None
        assert info["name"] == "ollama"
        assert info["available"] is True
        assert info["fallback_position"] == 0

    def test_get_provider_info_nonexistent(self):
        """Test getting info for nonexistent provider."""
        registry = ProviderRegistry()

        info = registry.get_provider_info("nonexistent")

        assert info is None

    def test_get_all_provider_info(self):
        """Test getting info for all providers."""
        registry = ProviderRegistry()
        registry.register(MockProvider(name="ollama", available=True))
        registry.register(MockProvider(name="claude", available=False))
        registry.set_fallback_chain(["ollama", "claude"])

        all_info = registry.get_all_provider_info()

        assert len(all_info) == 2

        ollama_info = next(p for p in all_info if p["name"] == "ollama")
        assert ollama_info["available"] is True
        assert ollama_info["fallback_position"] == 0

        claude_info = next(p for p in all_info if p["name"] == "claude")
        assert claude_info["available"] is False
        assert claude_info["fallback_position"] == 1


class TestRegistrySingleton:
    """Test registry singleton behavior."""

    def test_registry_is_independent(self):
        """Test each registry instance is independent."""
        registry1 = ProviderRegistry()
        registry2 = ProviderRegistry()

        registry1.register(MockProvider(name="test1"))

        assert "test1" in registry1.list_providers()
        assert "test1" not in registry2.list_providers()
