"""
Unit tests for CodegenService.

Sprint 45: Multi-Provider Codegen Architecture (EP-06)
Tests for codegen_service.py functionality.

Author: Backend Lead
Date: December 23, 2025
"""

import pytest
from unittest.mock import patch, AsyncMock, MagicMock
from typing import Dict, Any

from app.services.codegen.codegen_service import (
    CodegenService,
    NoProviderAvailableError,
    GenerationError,
    get_codegen_service
)
from app.services.codegen.provider_registry import ProviderRegistry
from app.services.codegen.base_provider import (
    CodegenProvider,
    CodegenSpec,
    CodegenResult,
    ValidationResult,
    CostEstimate
)


class MockProvider(CodegenProvider):
    """Mock provider for testing."""

    def __init__(
        self,
        name: str,
        available: bool = True,
        should_fail: bool = False,
        is_stub: bool = False
    ):
        self._name = name
        self._available = available
        self._should_fail = should_fail
        self._is_stub = is_stub

    @property
    def name(self) -> str:
        return self._name

    @property
    def is_available(self) -> bool:
        return self._available

    async def generate(self, spec: CodegenSpec) -> CodegenResult:
        if self._is_stub:
            raise NotImplementedError(f"{self._name} is stub")
        if self._should_fail:
            raise Exception("Generation failed")
        return CodegenResult(
            code=f"# Generated by {self._name}",
            files={"main.py": "# code"},
            provider=self._name,
            tokens_used=100,
            generation_time_ms=500
        )

    async def validate(
        self, code: str, context: Dict[str, Any]
    ) -> ValidationResult:
        if self._is_stub:
            raise NotImplementedError("Validation not implemented")
        return ValidationResult(valid=True)

    def estimate_cost(self, spec: CodegenSpec) -> CostEstimate:
        costs = {"cheap": 0.001, "expensive": 0.10}
        return CostEstimate(
            estimated_tokens=1000,
            estimated_cost_usd=costs.get(self._name, 0.01),
            provider=self._name,
            confidence=0.8
        )


class TestCodegenServiceInit:
    """Tests for CodegenService initialization."""

    def test_init_with_auto_register(self):
        """Test auto-registration of providers."""
        with patch.object(
            CodegenService, '_register_default_providers'
        ) as mock_register:
            service = CodegenService(auto_register=True)
            mock_register.assert_called_once()

    def test_init_without_auto_register(self):
        """Test initialization without auto-registration."""
        with patch.object(
            CodegenService, '_register_default_providers'
        ) as mock_register:
            service = CodegenService(auto_register=False)
            mock_register.assert_not_called()

    def test_init_with_custom_registry(self):
        """Test initialization with custom registry."""
        custom_registry = ProviderRegistry()
        service = CodegenService(
            custom_registry=custom_registry,
            auto_register=False
        )
        assert service._registry is custom_registry


class TestCodegenServiceProviders:
    """Tests for provider management."""

    @pytest.fixture
    def service(self):
        """Create service with mock registry."""
        registry = ProviderRegistry()
        registry.register(MockProvider("ollama", available=True))
        registry.register(MockProvider("claude", available=False))
        registry.set_fallback_chain(["ollama", "claude"])

        return CodegenService(custom_registry=registry, auto_register=False)

    def test_list_providers(self, service):
        """Test listing providers."""
        providers = service.list_providers()

        assert len(providers) == 2

        ollama = next(p for p in providers if p["name"] == "ollama")
        assert ollama["available"] is True
        assert ollama["primary"] is True

        claude = next(p for p in providers if p["name"] == "claude")
        assert claude["available"] is False

    def test_get_available_providers(self, service):
        """Test getting available providers."""
        available = service.get_available_providers()

        assert "ollama" in available
        assert "claude" not in available

    def test_set_fallback_chain(self, service):
        """Test setting custom fallback chain."""
        service.set_fallback_chain(["claude", "ollama"])

        health = service.health_check()
        assert health["fallback_chain"] == ["claude", "ollama"]

    def test_health_check(self, service):
        """Test health check."""
        health = service.health_check()

        assert health["healthy"] is True
        assert health["available_count"] == 1
        assert health["total_count"] == 2
        assert health["providers"]["ollama"] is True
        assert health["providers"]["claude"] is False


class TestCodegenServiceGenerate:
    """Tests for generate method."""

    @pytest.fixture
    def spec(self):
        """Create test spec."""
        return CodegenSpec(
            app_blueprint={"name": "Test", "modules": []}
        )

    @pytest.mark.asyncio
    async def test_generate_success(self, spec):
        """Test successful generation."""
        registry = ProviderRegistry()
        registry.register(MockProvider("ollama"))
        registry.set_fallback_chain(["ollama"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = await service.generate(spec)

        assert isinstance(result, CodegenResult)
        assert result.provider == "ollama"
        assert "main.py" in result.files

    @pytest.mark.asyncio
    async def test_generate_with_preferred_provider(self, spec):
        """Test generation with preferred provider."""
        registry = ProviderRegistry()
        registry.register(MockProvider("ollama"))
        registry.register(MockProvider("claude"))
        registry.set_fallback_chain(["ollama", "claude"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = await service.generate(spec, preferred_provider="claude")

        assert result.provider == "claude"

    @pytest.mark.asyncio
    async def test_generate_fallback_on_stub(self, spec):
        """Test fallback when provider is stub."""
        registry = ProviderRegistry()
        registry.register(MockProvider("stub", is_stub=True))
        registry.register(MockProvider("working"))
        registry.set_fallback_chain(["stub", "working"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = await service.generate(spec, preferred_provider="stub")

        assert result.provider == "working"

    @pytest.mark.asyncio
    async def test_generate_no_providers_error(self, spec):
        """Test error when no providers available."""
        registry = ProviderRegistry()
        registry.register(MockProvider("down", available=False))
        registry.set_fallback_chain(["down"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        with pytest.raises(NoProviderAvailableError):
            await service.generate(spec)

    @pytest.mark.asyncio
    async def test_generate_error_wrapping(self, spec):
        """Test generation errors are wrapped."""
        registry = ProviderRegistry()
        registry.register(MockProvider("failing", should_fail=True))
        registry.set_fallback_chain(["failing"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        with pytest.raises(GenerationError) as exc_info:
            await service.generate(spec)

        assert exc_info.value.provider == "failing"
        assert exc_info.value.original_error is not None


class TestCodegenServiceValidate:
    """Tests for validate method."""

    @pytest.mark.asyncio
    async def test_validate_success(self):
        """Test successful validation."""
        registry = ProviderRegistry()
        registry.register(MockProvider("ollama"))
        registry.set_fallback_chain(["ollama"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = await service.validate(
            code="def foo(): pass",
            context={"language": "python"}
        )

        assert isinstance(result, ValidationResult)
        assert result.valid is True

    @pytest.mark.asyncio
    async def test_validate_stub_provider_defaults_valid(self):
        """Test validation defaults to valid for stub providers."""
        registry = ProviderRegistry()
        registry.register(MockProvider("stub", is_stub=True))
        registry.set_fallback_chain(["stub"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = await service.validate(code="test", context={})

        assert result.valid is True
        assert len(result.warnings) == 1
        assert "stub" in result.warnings[0]

    @pytest.mark.asyncio
    async def test_validate_no_providers_error(self):
        """Test error when no providers for validation."""
        registry = ProviderRegistry()
        registry.register(MockProvider("down", available=False))
        registry.set_fallback_chain(["down"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        with pytest.raises(NoProviderAvailableError):
            await service.validate(code="test", context={})


class TestCodegenServiceCostEstimate:
    """Tests for cost estimation methods."""

    @pytest.fixture
    def service(self):
        """Create service with providers of different costs."""
        registry = ProviderRegistry()
        registry.register(MockProvider("cheap", available=True))
        registry.register(MockProvider("expensive", available=True))
        registry.register(MockProvider("unavailable", available=False))
        registry.set_fallback_chain(["cheap", "expensive"])

        return CodegenService(custom_registry=registry, auto_register=False)

    @pytest.fixture
    def spec(self):
        """Create test spec."""
        return CodegenSpec(app_blueprint={"name": "Test"})

    def test_estimate_cost_all_providers(self, service, spec):
        """Test cost estimation for all providers."""
        estimates = service.estimate_cost(spec)

        assert "cheap" in estimates
        assert "expensive" in estimates
        assert "unavailable" in estimates

    def test_estimate_cost_specific_providers(self, service, spec):
        """Test cost estimation for specific providers."""
        estimates = service.estimate_cost(spec, provider_names=["cheap"])

        assert "cheap" in estimates
        assert "expensive" not in estimates

    def test_get_cheapest_provider(self, service, spec):
        """Test finding cheapest available provider."""
        result = service.get_cheapest_provider(spec)

        assert result is not None
        name, estimate = result
        assert name == "cheap"
        assert estimate.estimated_cost_usd == 0.001

    def test_get_cheapest_provider_none_available(self, spec):
        """Test cheapest provider when none available."""
        registry = ProviderRegistry()
        registry.register(MockProvider("down", available=False))
        registry.set_fallback_chain(["down"])

        service = CodegenService(custom_registry=registry, auto_register=False)

        result = service.get_cheapest_provider(spec)

        assert result is None


class TestCodegenServiceSingleton:
    """Tests for singleton pattern."""

    def test_get_codegen_service_singleton(self):
        """Test get_codegen_service returns singleton."""
        # Reset global
        import app.services.codegen.codegen_service as module
        module._service = None

        service1 = get_codegen_service()
        service2 = get_codegen_service()

        assert service1 is service2

        # Cleanup
        module._service = None
